# Generated by Django 2.0 on 2018-01-12 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('ContentsSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='품목내부코드')),
                ('ContentsNo', models.CharField(max_length=20, unique=True, verbose_name='SerialNo')),
                ('ContentsName', models.CharField(max_length=20, unique=True, verbose_name='ContentsName')),
                ('RegNo', models.CharField(max_length=20, unique=True, verbose_name='장비종류')),
                ('Director', models.CharField(max_length=20, unique=True, verbose_name='모델')),
                ('MainActors', models.CharField(max_length=20, unique=True, verbose_name='MAC')),
                ('FileName', models.CharField(max_length=50, unique=True, verbose_name='수령일시')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '영화',
                'verbose_name_plural': '영화',
            },
        ),
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('CustSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='거래처내부코드')),
                ('CustNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='거래처번호')),
                ('CustName', models.CharField(blank=True, max_length=20, null=True, verbose_name='거래처명')),
                ('CutFullName', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자거래처명')),
                ('OwnerName', models.CharField(blank=True, max_length=20, null=True, verbose_name='대표자명')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
                ('RegUserSeq', models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('UptUserSeq', models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처',
            },
        ),
        migrations.CreateModel(
            name='DCode',
            fields=[
                ('DCodeSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='D코드내부코드')),
                ('DCodeName', models.CharField(blank=True, max_length=20, null=True, verbose_name='D코드명')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '공통코드D',
                'verbose_name_plural': '공통코드D',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('EmpSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='담당자내부코드')),
                ('EmpNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자번호')),
                ('EmpName', models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자명')),
                ('WorkDept', models.CharField(blank=True, max_length=20, null=True, verbose_name='근무부서')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
                ('RegUserSeq', models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('UptUserSeq', models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('WorkCompany', models.ForeignKey(db_column='WorkCompany', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Cust', verbose_name='소속')),
            ],
            options={
                'verbose_name': '사원',
                'verbose_name_plural': '사원',
            },
        ),
        migrations.CreateModel(
            name='InOutD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InOutSerl', models.IntegerField(verbose_name='입출고순번')),
                ('Qty', models.IntegerField(verbose_name='수량')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '입출고D',
                'verbose_name_plural': '입출고D',
            },
        ),
        migrations.CreateModel(
            name='InOutM',
            fields=[
                ('InOutSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='입출고내부코드')),
                ('InOutNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='입출고번호')),
                ('InOutDiv', models.IntegerField(verbose_name='입출고구분')),
                ('InOutDate', models.DateField(verbose_name='입출고일')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '입출고',
                'verbose_name_plural': '입출고',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='품목내부코드')),
                ('SerialNo', models.CharField(max_length=20, unique=True, verbose_name='SerialNo')),
                ('HWSerialNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='HWSerialNo')),
                ('MacAddr', models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RcvDate', models.DateTimeField(blank=True, null=True, verbose_name='수령일시')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
                ('ItemTypeSeq', models.ForeignKey(db_column='ItemTypeSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.DCode', verbose_name='장비종류')),
                ('ModelSeq', models.ForeignKey(db_column='ModelSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.DCode', verbose_name='모델')),
                ('RcvEmpSeq', models.ForeignKey(db_column='RcvEmpSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Emp', verbose_name='수령자')),
                ('RegUserSeq', models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('UptUserSeq', models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '품목',
                'verbose_name_plural': '품목',
            },
        ),
        migrations.CreateModel(
            name='MCode',
            fields=[
                ('MCodeSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='M코드내부코드')),
                ('MCodeNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='M코드번호')),
                ('MCodeName', models.CharField(blank=True, max_length=20, null=True, verbose_name='M코드명')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
                ('RegUserSeq', models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('UptUserSeq', models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '공통코드M',
                'verbose_name_plural': '공통코드M',
            },
        ),
        migrations.CreateModel(
            name='PhysicalInvD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PInvSerl', models.IntegerField(verbose_name='재고실사순번')),
                ('Qty', models.IntegerField(verbose_name='수량')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
                ('ItemSeq', models.ForeignKey(db_column='ItemSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Item', verbose_name='품목코드')),
            ],
            options={
                'verbose_name': '재고실사D',
                'verbose_name_plural': '재고실사D',
            },
        ),
        migrations.CreateModel(
            name='PhysicalInvM',
            fields=[
                ('PInvSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='재고실사내부번호')),
                ('PInvNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='재고실사번호')),
                ('PInvDate', models.CharField(blank=True, max_length=20, null=True, verbose_name='재고실사일')),
                ('SrtTime', models.TimeField(blank=True, null=True, verbose_name='시작시간')),
                ('EndTim', models.TimeField(blank=True, null=True, verbose_name='종료시간')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
                ('PInvType', models.ForeignKey(db_column='PInvType', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.DCode', verbose_name='재고실사종류')),
                ('RegUserSeq', models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('UptUserSeq', models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '재고실사',
                'verbose_name_plural': '재고실사',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WH',
            fields=[
                ('WHSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='창고내부코드')),
                ('WHNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='창고번호')),
                ('WHName', models.CharField(blank=True, max_length=20, null=True, verbose_name='창고명')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
                ('RegUserSeq', models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('UptUserSeq', models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '창고',
                'verbose_name_plural': '창고',
            },
        ),
        migrations.AddField(
            model_name='physicalinvm',
            name='WHSeq',
            field=models.ForeignKey(db_column='WHSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.WH', verbose_name='창고'),
        ),
        migrations.AddField(
            model_name='physicalinvm',
            name='WorkEmpSeq',
            field=models.ForeignKey(db_column='WorkEmpSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Emp', verbose_name='작업자'),
        ),
        migrations.AddField(
            model_name='physicalinvd',
            name='PInvSeq',
            field=models.ForeignKey(db_column='PInvSeq', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='VRMApp.PhysicalInvM', verbose_name='재고실사내부번호'),
        ),
        migrations.AddField(
            model_name='physicalinvd',
            name='RegUserSeq',
            field=models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='physicalinvd',
            name='SerialNo',
            field=models.ForeignKey(db_column='SerialNo', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Item', to_field='SerialNo', verbose_name='SerialNo'),
        ),
        migrations.AddField(
            model_name='physicalinvd',
            name='UptUserSeq',
            field=models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='inoutm',
            name='InWHSeq',
            field=models.ForeignKey(db_column='InWHSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.WH', verbose_name='입고창고'),
        ),
        migrations.AddField(
            model_name='inoutm',
            name='OutWHSeq',
            field=models.ForeignKey(db_column='OutWHSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.WH', verbose_name='출고창고'),
        ),
        migrations.AddField(
            model_name='inoutm',
            name='RegUserSeq',
            field=models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='inoutm',
            name='UptUserSeq',
            field=models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='inoutd',
            name='InOutSeq',
            field=models.ForeignKey(db_column='InOutSeq', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='VRMApp.InOutM', verbose_name='입출고Seq'),
        ),
        migrations.AddField(
            model_name='inoutd',
            name='ItemSeq',
            field=models.ForeignKey(db_column='ItemSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Item', verbose_name='품목코드'),
        ),
        migrations.AddField(
            model_name='inoutd',
            name='RegUserSeq',
            field=models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='inoutd',
            name='SerialNo',
            field=models.ForeignKey(db_column='SerialNo', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Item', to_field='SerialNo', verbose_name='SerialNo'),
        ),
        migrations.AddField(
            model_name='inoutd',
            name='UptUserSeq',
            field=models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='dcode',
            name='MCodeSeq',
            field=models.ForeignKey(db_column='MCodeSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.MCode', verbose_name='M코드'),
        ),
        migrations.AddField(
            model_name='dcode',
            name='RegUserSeq',
            field=models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='dcode',
            name='UptUserSeq',
            field=models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='contents',
            name='MakerSeq',
            field=models.ForeignKey(db_column='MakerSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Cust', verbose_name='제작사'),
        ),
        migrations.AddField(
            model_name='contents',
            name='RegUserSeq',
            field=models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contents',
            name='UptUserSeq',
            field=models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterUniqueTogether(
            name='inoutd',
            unique_together={('InOutSeq', 'InOutSerl')},
        ),
    ]
