# Generated by Django 2.0 on 2018-01-12 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VRMApp', '0004_auto_20180112_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayDate', models.DateField(verbose_name='상영일')),
                ('PlayOrder', models.IntegerField(verbose_name='회차')),
                ('PlaySerl', models.IntegerField(verbose_name='영화')),
                ('StrTime', models.TimeField(blank=True, null=True, verbose_name='시작시간')),
                ('EndTime', models.TimeField(blank=True, null=True, verbose_name='종료일')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
                ('ContentsSeq', models.ForeignKey(db_column='ContentsSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Contents', verbose_name='영화')),
                ('RegUserSeq', models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('UptUserSeq', models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '상영계획',
                'verbose_name_plural': '상영계획',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.AlterUniqueTogether(
            name='playplan',
            unique_together={('PlayDate', 'PlayOrder', 'PlaySerl')},
        ),
    ]
