# Generated by Django 2.0 on 2018-01-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VRMApp', '0006_auto_20180112_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='MakerSeq',
            field=models.ForeignKey(blank=True, db_column='MakerSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VRMApp.Cust', verbose_name='제작사'),
        ),
    ]
