# Generated by Django 2.0 on 2018-01-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRMApp', '0007_auto_20180112_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='ContentsEngName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='영등위등록번호'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='ContentsName',
            field=models.CharField(max_length=50, unique=True, verbose_name='제목'),
        ),
    ]
