# Generated by Django 2.0 on 2018-01-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRMApp', '0008_auto_20180112_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='PlayRate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='상영등급'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='ContentsEngName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='영문제목'),
        ),
    ]
